---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: local.intranet.dev
vagrant_machine_name: intranet
vagrant_webroot: /var/www/drupal
vagrant_ip: 10.10.10.10

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# Synced Folders
vagrant_synced_folders:
  - local_path: ~/Sites/intranet
    destination: /var/www
    id: drupal
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

ansible_os_family: Debian
#ansible_os_family: RedHat

# Server Extras
installed_extras:
  - mailhogx
  - memcached
  - phpmyadmin
  - pimpmylog
  - xdebug
  - xhprof
  - drupal
  # - solr
  # - selenium
  # - nodejs
  # - varnish

# Intranet Modules
intranet_modules:
  - common  
  # - sales
  # - research  
  # - team_members
  # - projects
  # - contracts  
  # - finance
  # - clients