---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.intranet.dev
vagrant_ip: 10.10.10.11
vagrant_user: vagrant
vagrant_home: /home/vagrant
vagrant_webroot: /var/www/drupal

# Synced Folders
vagrant_synced_folders:
  - local_path: ~/Sites/intranet
    destination: /var/www
    id: drupal
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

ansible_os_family: Debian
#ansible_os_family: RedHat

# Server Extras
installed_extras:
  - mailhogx
  - memcached
  - phpmyadmin
  - pimpmylog
  - xdebug
  - xhprof
  - drupal
  # - solr
  # - selenium
  # - nodejs
  # - varnish

# Intranet Modules
intranet_modules:
  - common  
  # - sales
  # - research  
  # - team_members
  # - projects
  # - contracts  
  # - finance
  # - clients