---
# PHP Configuration. 
php_version: "5.4"
php_memory_limit: "1024M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# APC will be enabled for PHP < 5.5, OpCache for PHP 5.5+.
php_apc_enabled_in_ini: true
php_apc_shm_size: "128M"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "128"
php_opcache_max_accelerated_files: 4096